name: Build

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: macos-latest

    steps:

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "18.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.2'

      - name: Get Flutter packages
        run: |
          flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release --flavor prod --target lib/main_prod.dart

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-prod-release.apk
